# ByteForge App Generation System Configuration
# For ByteForge Project

# Project Information
project:
  name: "LSOMigrator"
  description: "LSM to CLX Data Migration System"
  version: "1.0.0"
  client: "ContractLogix"

# Input/Output Paths (relative to project root for cross-platform compatibility)
paths:
  # Universal Path Structure - ALWAYS relative to Requirements_Generation_System
  # ByteForgePath = {relative_path}\ByteForge (parent directory)
  byteforge_path: ".."

  # ByteForgeProjectPath = {ByteForgePath}\project
  byteforge_project_path: "../project"

  # All generated content goes under ByteForgeProjectPath
  requirements_dir: "../project/requirements_artifacts"
  output_dir: "../project/requirements"
  status_dir: "../project/generation_status"
  design_dir: "../project/design"
  code_dir: "../project/code"

  # Prompt templates directory (relative to Requirements_Generation_System)
  prompts_dir: "../Requirements_Generation_Prompts"

  # Source code directories for full regeneration
  frontend_dir: "FrontEnd"
  backend_dir: "BackEnd"

# LLM Configuration
llm:
  # Primary provider: openai, anthropic, gemini, or grok
  provider: "openai"

  # Model selection (can be overridden at runtime)
  # OpenAI options: "o3", "o3-mini", "gpt-4o", etc.
  openai_model: "o3-mini"
  anthropic_model: "claude-sonnet-4-20250514"
  gemini_model: "gemini-2.5-pro-preview-06-05"
  grok_model: "grok-beta"

  # Temperature for generation (0.0-1.0) - optimized for code generation
  temperature: 0.2

  # Maximum tokens per request - increased for better context
  max_tokens: 8000

  # Request timeout in seconds - optimized for claude-sonnet-4
  timeout: 240

  # Extended timeout for o3 models (seconds) - o3 models need longer due to reasoning
  o3_timeout: 300

  # Claude Code specific settings
  claude_code:
    # Model for claude code execution
    model: "claude-sonnet-4-20250514"
    # Temperature for code generation (lower for consistency)
    temperature: 0.1
    # Timeout for claude code operations (seconds)
    timeout: 600
    # Maximum retries for failed executions
    max_retries: 3
    # Retry delay in seconds
    retry_delay: 10

  # Retry configuration
  max_retries: 3
  retry_delay: 5

# Dual-LLM Review System Configuration
review_system:
  # Enable dual-LLM review system
  enabled: true

  # Primary LLM configuration (for initial document generation)
  primary_llm:
    provider: "openai"
    model: "o3-mini"
    temperature: 0.7
    max_tokens: 4000

  # Reviewer LLM configuration (for document review and improvement)
  reviewer_llm:
    provider: "gemini"
    model: "gemini-2.5-pro-preview-06-05"
    temperature: 0.5  # Lower temperature for more consistent reviews
    max_tokens: 8192  # Higher token limit for comprehensive reviews

  # Review process settings
  review_settings:
    # Enable review step after validation
    auto_review: true

    # Maximum number of review iterations
    max_review_iterations: 1

    # Skip review for certain document types (if needed)
    skip_review_for: []

    # Review prompt customization
    preserve_structure: true
    preserve_length: true
    focus_on_accuracy: true
    add_missing_details: true

# Document Generation Settings
generation:
  # Number of refinement rounds (1-5)
  refinement_rounds: 3
  
  # Enable parallel processing
  parallel_processing: false
  
  # Maximum concurrent generations
  max_concurrent: 2
  
  # Validation strictness (low, medium, high)
  validation_level: "high"
  
  # Save intermediate versions
  save_drafts: true
  
  # Include metadata in documents
  include_metadata: true

# Document Types Configuration
documents:
  # Business Requirements Document
  BRD:
    enabled: true
    priority: 1
    dependencies: []
    
  # Product Requirements Document  
  PRD:
    enabled: true
    priority: 2
    dependencies: ["BRD"]
    
  # Functional Requirements Document
  FRD:
    enabled: true
    priority: 3
    dependencies: ["PRD"]
    
  # Non-Functional Requirements Document
  NFRD:
    enabled: true
    priority: 3
    dependencies: ["PRD"]
    
  # Design Requirements Document
  DRD:
    enabled: true
    priority: 4
    dependencies: ["FRD", "NFRD"]
    
  # Database Schema
  DB_SCHEMA:
    enabled: true
    priority: 5
    dependencies: ["DRD"]
    
  # Technical Requirements Document
  TRD:
    enabled: true
    priority: 5
    dependencies: ["DRD"]
    
  # API Specification
  API_SPEC:
    enabled: true
    priority: 6
    dependencies: ["TRD"]
    
  # Test Plan
  TEST_PLAN:
    enabled: true
    priority: 7
    dependencies: ["FRD", "API_SPEC"]
    
  # Requirements Traceability Matrix
  RTM:
    enabled: true
    priority: 8
    dependencies: ["TEST_PLAN"]

# Traceability Configuration
traceability:
  # ID format patterns
  id_patterns:
    BRD: "BRD-{:03d}"
    PRD: "PRD-{:03d}"
    FRD: "FRD-{:03d}.{:d}"
    NFRD: "NFRD-{:03d}.{:d}"
    DRD: "DRD-{:03d}.{:d}.{:d}"
    TRD: "TRD-{:03d}.{:d}.{:d}"
    TC: "TC-{:03d}.{:d}.{:d}.{:d}"
    API: "API-{:03d}.{:d}"
    DB: "DB-{:03d}.{:d}"
    
  # Enable bidirectional linking
  bidirectional: true
  
  # Validate all references
  validate_references: true

# Monitoring Configuration
monitoring:
  # Enable real-time monitoring
  enabled: true
  
  # Update frequency in seconds
  refresh_rate: 2
  
  # Generate progress graphs
  generate_graphs: true
  
  # Export metrics
  export_metrics: true

# Notification Settings
notifications:
  # Enable notifications
  enabled: false
  
  # Notification methods
  methods:
    - console
    - file
    
  # Events to notify
  events:
    - generation_started
    - document_completed
    - generation_failed
    - all_completed

# Advanced Settings
advanced:
  # Context window management
  context_strategy: "sliding"  # full, sliding, or summary

  # Chunk size for large documents
  chunk_size: 3000

  # Enable caching
  enable_cache: true

  # Cache TTL in hours
  cache_ttl: 24

  # Debug mode
  debug: false

  # Verbose logging
  verbose: true

# Claude Code Execution Configuration
claude_code_execution:
  # WSL Configuration
  wsl:
    # WSL distribution name
    distribution: "Ubuntu"
    # Base mount path for Windows drives
    mount_prefix: "/mnt"
    # Default shell
    shell: "bash"

  # Execution Settings
  execution:
    # Default working directory (relative to project root)
    working_directory: "."
    # Command prefix for claude code
    command_prefix: "claude"
    # Default flags
    default_flags: ["--model", "sonnet", "--dangerously-skip-permissions"]
    # Maximum execution time per agent (minutes)
    max_execution_time: 60
    # Maximum prompt size (characters)
    max_prompt_size: 50000

  # Agent Configuration
  agents:
    backend:
      name: "Backend Agent"
      description: "ASP.NET Core API, data models, business logic"
      directory: "BackEnd"
      priority: 1
      estimated_duration: 45
    frontend:
      name: "Frontend Agent"
      description: "React/Next.js user interface components"
      directory: "FrontEnd"
      priority: 2
      estimated_duration: 40
    security:
      name: "Security Agent"
      description: "Authentication, authorization, audit logging"
      directory: "BackEnd"
      priority: 3
      estimated_duration: 30
    infrastructure:
      name: "Infrastructure Agent"
      description: "Azure resources, CI/CD, containerization"
      directory: "Infrastructure"
      priority: 4
      estimated_duration: 35
    integration:
      name: "Integration Agent"
      description: "API integration, data synchronization, external services"
      directory: "BackEnd"
      priority: 5
      estimated_duration: 30

  # Phase Configuration
  phases:
    phase1:
      name: "MVP Core Features"
      description: "Implement core functionality for minimum viable product"
      priority: 1
      estimated_duration: 180
      dependencies: {}
    phase2:
      name: "Advanced Features"
      description: "Add advanced functionality and business logic"
      priority: 2
      estimated_duration: 150
      dependencies:
        backend: ["backend-phase1"]
        frontend: ["backend-phase2", "frontend-phase1"]
        security: ["backend-phase2", "security-phase1"]
        infrastructure: ["infrastructure-phase1"]
        integration: ["backend-phase2", "frontend-phase2", "security-phase2"]
    phase3:
      name: "Production Ready"
      description: "Production hardening, performance, monitoring"
      priority: 3
      estimated_duration: 120
      dependencies:
        backend: ["infrastructure-phase3", "backend-phase2"]
        frontend: ["infrastructure-phase3", "frontend-phase2"]
        security: ["infrastructure-phase3", "security-phase2"]
        infrastructure: ["infrastructure-phase2"]
        integration: ["backend-phase3", "frontend-phase3", "security-phase3"]

  # Monitoring and Logging
  monitoring:
    # Enable real-time progress monitoring
    enabled: true
    # Log file paths
    log_directory: "logs"
    # Progress tracking file
    progress_file: "progress_tracker.json"
    # Execution plan file
    execution_plan_file: "execution_plan.md"
    # Update frequency (seconds)
    update_frequency: 5

  # Error Handling and Recovery
  error_handling:
    # Enable automatic retry on failure
    auto_retry: true
    # Maximum retry attempts
    max_retries: 3
    # Retry delay (seconds)
    retry_delay: 30
    # Enable rollback on critical failure
    auto_rollback: false
    # Save error logs
    save_error_logs: true

# Full Regeneration from Code Settings
code_regeneration:
  # Batching configuration for processing code files
  batching:
    # Maximum number of files to process in a single batch
    max_files: 12

    # Maximum tokens per batch (to stay within LLM context limits)
    max_tokens: 8000

    # File extensions to include when scanning code directories
    included_extensions:
      - ".ts"
      - ".tsx"
      - ".js"
      - ".jsx"
      - ".cs"
      - ".cshtml"
      - ".sql"
      - ".bicep"
      - ".md"
      - ".json"
      - ".yaml"
      - ".yml"

    # Directories to exclude from scanning
    excluded_directories:
      - "node_modules"
      - "bin"
      - "obj"
      - "dist"
      - "build"
      - ".git"
      - ".vs"
      - ".vscode"
      - "temp"
      - "logs"
      - "coverage"

    # Files to exclude from scanning (by name)
    excluded_files:
      - "package-lock.json"
      - "yarn.lock"
      - "*.min.js"
      - "*.min.css"
      - "*.map"

  # Directories to purge during full regeneration
  purge_directories:
    - "generated_documents"
    - "generation_status"
    - "Requirements/consolidated-requirements"
    - "Requirements/invoice-requirements"
    - "Requirements/logistics-requirements"
    - "Requirements_Generation_System/build_passes"

# AI-Driven Application Builder Configuration
application_builder:
  # Enable the application builder system
  enabled: true

  # Maximum retries per pass
  max_retries: 4

  # Timeout for each pass in minutes
  timeout_minutes: 30

  # AI Pass Configuration
  passes:
    # Pass 1: Design Phase (OpenAI o3)
    design:
      model: "openai"
      model_name: "o3-mini"
      temperature: 0.2
      max_tokens: 4000
      timeout_seconds: 300

    # Pass 2: Review Phase (Gemini 2.5)
    review:
      model: "gemini"
      model_name: "gemini-2.5-pro-preview-06-05"
      temperature: 0.1
      max_tokens: 3000
      timeout_seconds: 240

    # Pass 3: Implementation Phase (Claude Sonnet 4)
    implementation:
      model: "anthropic"
      model_name: "claude-sonnet-4-20250514"
      temperature: 0.1
      max_tokens: 8000
      timeout_seconds: 600

    # Pass 4: Alternative Implementation Phase (Grok)
    grok_implementation:
      model: "grok"
      model_name: "grok-beta"
      temperature: 0.1
      max_tokens: 8000
      timeout_seconds: 300

  # Build System Configuration
  build_system:
    # Frontend build configuration (Next.js)
    frontend:
      build_command: ["npm", "run", "build"]
      test_command: ["npm", "test", "--", "--watchAll=false"]
      dev_command: ["npm", "run", "dev"]
      install_command: ["npm", "install"]
      lint_command: ["npm", "run", "lint"]
      working_directory: "FrontEnd"

    # Backend build configuration (.NET Core)
    backend:
      build_command: ["dotnet", "build"]
      test_command: ["dotnet", "test"]
      run_command: ["dotnet", "run"]
      restore_command: ["dotnet", "restore"]
      clean_command: ["dotnet", "clean"]
      working_directory: "BackEnd"

  # Git Configuration
  git:
    # Automatically commit changes
    auto_commit: true

    # Branch naming prefix
    branch_prefix: "feature/ai-generated"

    # Automatically create pull requests
    create_pr: true

    # PR template file
    pr_template: "templates/pr_template.md"

    # Default base branch for PRs
    base_branch: "master"

    # Commit message template
    commit_message_template: "feat: {feature_name} - AI-generated implementation"

  # Logging Configuration
  logging:
    # Enable separate terminal windows for each pass
    separate_terminals: true

    # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    log_level: "INFO"

    # Enable real-time monitoring
    real_time_monitoring: true

    # Log file retention in days
    retention_days: 30

  # Safety and Error Handling
  safety:
    # Maximum execution time for entire workflow (minutes)
    max_workflow_time: 120

    # Enable automatic rollback on failure
    auto_rollback: true

    # Require confirmation for destructive operations
    require_confirmation: true

    # Maximum file size for code generation (MB)
    max_file_size_mb: 10

# Environment Variables (override with actual values)
environment:
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
  GROK_API_KEY: "${GROK_API_KEY}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
